version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    hostname: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTICSEARCH_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./volumes/elastic/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./volumes/elastic/elastic01/data:/usr/share/elasticsearch/data
      - ./volumes/elastic/elastic01/certs:/usr/share/elasticsearch/config/certs
      - ./volumes/elastic/elastic01/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      stack-net:
        ipv4_address: 172.100.22.4

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es02
    hostname: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./volumes/elastic/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./volumes/elastic/elastic02/data:/usr/share/elasticsearch/data
      - ./volumes/elastic/elastic02/certs:/usr/share/elasticsearch/config/certs
      - ./volumes/elastic/elastic02/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      stack-net:
        ipv4_address: 172.100.22.9

  es03:
    build: ./volumes/elastic/elastic03
    image: elasticsearch:7.6.2
    container_name: es03
    hostname: es03
    command: "./data/entrypoint.sh"
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./volumes/elastic/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./volumes/elastic/elastic03/data:/usr/share/elasticsearch/data
      - ./volumes/elastic/elastic03/certs:/usr/share/elasticsearch/config/certs
      - ./volumes/elastic/elastic03/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      stack-net:
        ipv4_address: 172.100.22.10

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    hostname: Kibana
    volumes:
      - ./volumes/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      stack-net:
        ipv4_address: 172.100.22.6
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    hostname: Logstash
    volumes:
      - ./volumes/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./volumes/logstash/conf.d:/etc/logstash/conf.d
      - ./volumes/logstash/patterns:/opt/logstash/patterns
    ports:
      - 5044:5044
    networks:
      stack-net:
        ipv4_address: 172.100.22.5
  
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.2
    container_name: apm-server
    hostname: APM-server
    volumes:
      - ./volumes/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - 8200:8200
    networks:
      stack-net:
        ipv4_address: 172.100.22.8

networks:
  stack-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.22.0/24