xpack.enabled: true

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

setup.kibana:
  host: "http://192.168.18.2:5601/kibana"

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: '${ELASTICSEARCH_PASSWORD:}'

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
